### ISSUE TITLE
Support for postgis ?

### ISSUE THREAD

**Issue by navidemad** [ankane/setup-postgres#12]
Hello, thanks for your github action, it is very useful for one of my project.
Is there any support for postgis so far ?

```yml
jobs:
  tests:
    runs-on: ubuntu-24.04
    env:
      ImageOS: ubuntu24 # Need for ankane/setup-postgres to detect default version of postgres to 16
    steps:
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 16
          config: |
            shared_preload_libraries = 'pg_stat_statements'
```

I think this would do the job with an additional just before run the postgresql systemctl:
`sudo apg-get install postgresql-16-postgis-3`

Perhaps an options on the github actions like
`with_postgis: true/false`
to subtitute the package name to add a suffix `-postgis-3` ?

Best regards
